# 配置端口号
server:
  port: 8003
# mybatis配置
mybatis:
  type-aliases-package: com.study.springcould.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
# Spring配置
spring:
  application:
    name: springcould-provider-dept # 3个服务名称一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db03?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
# Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcould-provider-dept-8003 #修改Eureka上的默认描述信息
# info配置
info:
  app.name: jzhao-springcould
  company.name: aostar
